name: Deploy Java App to Tomcat

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use 'temurin' as the distribution
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_URL: http://your_server_ip:8080
      run: |
        curl -T target/car-booking.webapp.war "http://$TOMCAT_USERNAME:$TOMCAT_PASSWORD@$TOMCAT_URL/manager/text/deploy?path=/your-app&update=true"
