name: Deploy Java App to Tomcat

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        TOMCAT_URL: ${{ secrets.TOMCAT_URL }}
      run: |
        curl -u $TOMCAT_USERNAME:$TOMCAT_PASSWORD -T target/car-booking.webapp.war "$TOMCAT_URL/manager/text/deploy?path=/car-booking&update=true"
