name: Deploy to Tomcat

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build WAR file
        # Use your preferred build tool command (Maven or Gradle)
        run: mvn clean package
      - name: Deploy to Tomcat
        uses: actions/ssh-agent@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        steps:
          - uses: actions/checkout@v3
          - name: Deploy WAR
            run: |
              scp target/*.war user@your_server_ip:/path/to/tomcat/webapps
