name: Deploy Java App to Tomcat

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to Tomcat
      env:
        TOMCAT_USERNAME: ${{ secrets.admin }}
        TOMCAT_PASSWORD: ${{ secrets.admin }}
        TOMCAT_URL: http://18.191.10.172:8080
      run: |
        curl -T target/car-booking.webapp.war "http://$admin:$admin@$http://18.191.10.172:8080/manager/text/deploy?path=/your-app&update=true"
